version: 2
jobs:
  build:
    working_directory: /www/api
    docker:
      - image: php:alpine
    environment:
      - PHP: "php"
      - EMULATION: "true"
    steps:
      - checkout:
          path: /tmp/bm
      - run:
          name: move files to corresponding dirs
          command: 'for a in etc usr www; do find /tmp/bm/root/$a -type f -print0 | xargs -0 mv -t /$a; done'
      - run:
          name: make file for components communication
          command: 'mknod /tmp/breadmaker_from_device p'
      - run:
          name: add executable flag to breadmaker
          command: 'chmod 0777 /usr/share/breadmaker/breadmaker.sh'
      - run:
          name: install nmp dependencies
          command: 'curl -sSL https://phar.phpunit.de/phpunit.phar -o phpunit.phar && chmod +x phpunit.phar && mv phpunit.phar /usr/local/bin/phpunit'
      - run:
          name: run tests
          command: 'phpunit .'
